# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0007_auto_20171013_0821'),
        ('app_author', '0002_auto_20171007_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='app_forum.Comment'),
        ),
    ]
