# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0007_auto_20171013_0821'),
        ('app_author', '0003_profile_profile_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_comments',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_comments',
            field=models.ManyToManyField(related_name='profile_comments', to='app_forum.Comment'),
        ),
    ]
