# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0007_auto_20171013_0821'),
        ('app_author', '0004_auto_20171015_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_comments',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_comments',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='app_forum.Comment'),
            preserve_default=False,
        ),
    ]
