# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0006_auto_20171015_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_comments',
        ),
    ]
