# Generated by Django 2.0 on 2017-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0007_remove_profile_profile_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
