# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
