# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0002_comment_is_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
