# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0002_auto_20171007_1033'),
        ('app_forum', '0005_auto_20171013_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='forum_author',
        ),
        migrations.AddField(
            model_name='forum',
            name='forum_author',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_forums', to='app_author.Profile'),
        ),
    ]
