# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0002_auto_20171007_1033'),
        ('app_forum', '0006_auto_20171013_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_author',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='app_author.Profile'),
        ),
        migrations.RemoveField(
            model_name='forum',
            name='forum_author',
        ),
        migrations.AddField(
            model_name='forum',
            name='forum_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forums', to='app_author.Profile'),
        ),
    ]
