# Generated by Django 2.0 on 2017-12-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0007_auto_20171013_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_modified',
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
