# Generated by Django 2.2.13 on 2020-10-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0008_auto_20171204_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name_plural': 'Title'},
        ),
    ]
